const CONFIG={gameSeconds:3600,datasets:{"1-118":{label:"邢台公交 1–118",file:"1-118.txt"},"203-315":{label:"邢台公交 203–315",file:"203-315.txt"},rongda:{label:"融大公交",file:"rongda.txt"},pingxiang:{label:"平乡公交",file:"pingxiang.txt"},chengji:{label:"城际公交",file:"chengji.txt"}}};
const $=id=>document.getElementById(id);const els={loadStatus:$("loadStatus"),startPanel:$("startPanel"),gamePanel:$("gamePanel"),resultPanel:$("resultPanel"),startBtn:$("startBtn"),startTimer:$("startTimer"),startFound:$("startFound"),startRemaining:$("startRemaining"),startTotal:$("startTotal"),selectedDatasetCount:$("selectedDatasetCount"),datasetOptions:$("datasetOptions"),activeDatasets:$("activeDatasets"),resultDatasets:$("resultDatasets"),timer:$("timer"),foundCount:$("foundCount"),remainingCount:$("remainingCount"),totalCount:$("totalCount"),answerInput:$("answerInput"),foundList:$("foundList"),foundHint:$("foundHint"),giveUpBtn:$("giveUpBtn"),pauseBtn:$("pauseBtn"),resultFound:$("resultFound"),resultTotal:$("resultTotal"),resultFoundCount:$("resultFoundCount"),resultFoundList:$("resultFoundList"),completionRate:$("completionRate"),usedTime:$("usedTime"),resultTitle:$("resultTitle"),missedCount:$("missedCount"),missedList:$("missedList"),againBtn:$("againBtn"),resetBtn:$("resetBtn"),inputState:$("inputState")};
let datasetStations={},selectedDatasetKeys=[],allStations=[],remainingStations=[],foundStations=[],gameTimer=null,remainingSeconds=CONFIG.gameSeconds,paused=false,gameState="loading",composing=false;
const datasetLabel=k=>CONFIG.datasets[k]?.label||k;
function formatTime(t){t=Math.max(0,t);return `${Math.floor(t/60).toString().padStart(2,"0")}:${(t%60).toString().padStart(2,"0")}`}
function getSelectedKeys(){return [...els.datasetOptions.querySelectorAll('input[name="dataset"]:checked')].map(x=>x.value)}
function mergeSelectedStations(keys){const seen=new Set(),out=[];for(const k of keys)for(const s of datasetStations[k]||[]){if(!seen.has(s)){seen.add(s);out.push(s)}}return out}
function updateSelectionUI(){selectedDatasetKeys=getSelectedKeys();els.selectedDatasetCount.textContent=selectedDatasetKeys.length;const selected=mergeSelectedStations(selectedDatasetKeys);els.startTotal.textContent=selected.length||"—";els.startRemaining.textContent=selected.length||"—";els.startFound.textContent="0";els.startBtn.disabled=gameState==="loading"||!selected.length;els.datasetOptions.querySelectorAll(".dataset-card").forEach(c=>c.classList.toggle("selected",c.querySelector("input").checked))}
function renderDatasetPills(c,keys,mode){c.innerHTML="";keys.forEach(k=>{const e=document.createElement("span");e.className=`dataset-pill ${mode||""}`;e.textContent=datasetLabel(k);c.appendChild(e)})}
function updateStartStats(){const s=mergeSelectedStations(getSelectedKeys());els.startFound.textContent="0";els.startRemaining.textContent=s.length||"—";els.startTotal.textContent=s.length||"—";els.startTimer.textContent=formatTime(CONFIG.gameSeconds);updateSelectionUI()}
function updateGameStats(){els.timer.textContent=formatTime(remainingSeconds);els.foundCount.textContent=foundStations.length;els.remainingCount.textContent=remainingStations.length;els.totalCount.textContent=allStations.length;els.timer.classList.toggle("warning",remainingSeconds<=300&&remainingSeconds>60);els.timer.classList.toggle("danger",remainingSeconds<=60)}
async function loadOneDataset(k){const c=CONFIG.datasets[k];const url=new URL(c.file,document.baseURI);url.searchParams.set("v",Date.now().toString());const r=await fetch(url.toString(),{cache:"no-store"});if(!r.ok)throw new Error(`${c.file}: HTTP ${r.status}`);const t=await r.text();const a=t.replace(/^\uFEFF/,"").split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(!a.length)throw new Error(`${c.file} 中没有有效站名`);return [...new Set(a)]}
async function loadStations(){els.loadStatus.className="status";els.loadStatus.textContent="正在读取五个站名集……";els.startBtn.disabled=true;const results={};const errors=[];for(const k of Object.keys(CONFIG.datasets)){try{results[k]=await loadOneDataset(k)}catch(e){errors.push(e.message)}}if(errors.length){console.error("Station dataset loading failed:",errors);datasetStations={};gameState="loading";els.loadStatus.className="status error";els.loadStatus.innerHTML=`站名数据读取失败。<br>${errors.map(x=>`<span>${x}</span>`).join("<br>")}<br><small>请确认这 5 个 TXT 文件与 index.html 位于同一 GitHub Pages 目录，并检查文件名、大小写及实际内容。</small>`;els.startBtn.disabled=true;return}datasetStations=results;const raw=Object.values(datasetStations).reduce((n,a)=>n+a.length,0),unique=mergeSelectedStations(Object.keys(CONFIG.datasets)).length;els.datasetOptions.querySelectorAll("[data-dataset-count]").forEach(e=>e.textContent=`${datasetStations[e.dataset.datasetCount].length} 站`);gameState="ready";els.loadStatus.textContent=`DATA READY  ·  5 个站名集 · ${raw} 条数据 · ${unique} 个全局不重复站名`;els.loadStatus.className="status ok";updateStartStats()}
function startGame(){selectedDatasetKeys=getSelectedKeys();allStations=mergeSelectedStations(selectedDatasetKeys);if(!allStations.length){alert("请至少选择一个站名集。");return}clearInterval(gameTimer);remainingStations=[...allStations];foundStations=[];remainingSeconds=CONFIG.gameSeconds;paused=false;gameState="playing";els.startPanel.classList.add("hidden");els.resultPanel.classList.add("hidden");els.gamePanel.classList.remove("hidden");els.pauseBtn.textContent="暂停游戏";els.answerInput.value="";els.answerInput.disabled=false;els.foundList.innerHTML='<div class="list-empty">等待你的第一个答案</div>';els.foundList.classList.add("empty");els.foundHint.textContent="新发现会出现在最前面";renderDatasetPills(els.activeDatasets,selectedDatasetKeys,"active");setInputState("READY","请输入一个汉字或数字");updateGameStats();gameTimer=setInterval(()=>{if(paused||gameState!=="playing")return;remainingSeconds--;updateGameStats();if(remainingSeconds<=0){remainingSeconds=0;finishGame("时间到")}},1000);requestAnimationFrame(()=>els.answerInput.focus())}
function getValidCharacter(v){const chars=[...String(v||"")],valid=chars.filter(ch=>/[\u3400-\u9FFF0-9]/u.test(ch));return valid.length?valid[valid.length-1]:""}
function setInputState(title,text,type=""){if(!els.inputState)return;els.inputState.querySelector("strong").textContent=title;els.inputState.querySelector("span").textContent=text;els.inputState.className=`input-state ${type}`.trim()}
function submitCharacter(ch){if(gameState!=="playing"||paused||!ch)return;const matched=[],unmatched=[];for(const s of remainingStations)(s.includes(ch)?matched:unmatched).push(s);if(!matched.length){els.answerInput.value=ch;setInputState("NO MATCH",`“${ch}” 暂未找到对应站名`,"bad");els.foundHint.textContent=`没有站名包含“${ch}” · 继续尝试`;els.answerInput.focus();return}remainingStations=unmatched;foundStations=[...matched,...foundStations];renderFoundStations();updateGameStats();els.answerInput.value="";setInputState("MATCHED",`找到 ${matched.length} 个站名`,"good");els.answerInput.focus();if(!remainingStations.length)finishGame("全部猜出")}
function processInputValue(){if(composing||gameState!=="playing"||paused)return;const ch=getValidCharacter(els.answerInput.value);if(ch)submitCharacter(ch)}
function createStationElement(s){const e=document.createElement("span");e.className="station";e.textContent=s;return e}
function renderFoundStations(){els.foundList.classList.remove("empty");els.foundList.innerHTML="";if(!foundStations.length){els.foundList.classList.add("empty");els.foundList.innerHTML='<div class="list-empty">等待你的第一个答案</div>';return}foundStations.forEach((s,i)=>{const e=createStationElement(s);if(i<3)e.classList.add("recent");els.foundList.appendChild(e)});els.foundHint.textContent=`已发现 ${foundStations.length} 个 · 最新结果在最前面`}

function renderResultList(c,a,empty,cls){c.innerHTML="";c.className=`station-list ${cls}`.trim();if(!a.length){c.innerHTML=`<div class="list-empty">${empty}</div>`;return}a.forEach(s=>c.appendChild(createStationElement(s)))}
function togglePause(){if(!["playing","paused"].includes(gameState))return;paused=!paused;gameState=paused?"paused":"playing";els.pauseBtn.textContent=paused?"继续游戏":"暂停游戏";els.answerInput.disabled=paused;if(paused){els.answerInput.blur();setInputState("PAUSED","计时已暂停","pause")}else{setInputState("READY","请输入一个汉字或数字");els.answerInput.focus()}}
function finishGame(reason){if(gameState==="finished")return;clearInterval(gameTimer);gameTimer=null;gameState="finished";paused=false;const found=foundStations.length,total=allStations.length,rate=total?found/total*100:0,used=CONFIG.gameSeconds-remainingSeconds;els.gamePanel.classList.add("hidden");els.resultPanel.classList.remove("hidden");els.resultTitle.textContent=reason;els.resultFound.textContent=found;els.resultTotal.textContent=total;els.resultFoundCount.textContent=found;els.completionRate.textContent=`${rate.toFixed(0)}%`;els.usedTime.textContent=formatTime(used);els.missedCount.textContent=remainingStations.length;renderDatasetPills(els.resultDatasets,selectedDatasetKeys,"result");renderResultList(els.missedList,remainingStations,"没有遗漏，完美完成。","missed");renderResultList(els.resultFoundList,foundStations,"本局没有猜出站名。","result-found");window.scrollTo({top:0,behavior:"smooth"})}
function resetToReady(){clearInterval(gameTimer);gameTimer=null;allStations=[];remainingStations=[];foundStations=[];remainingSeconds=CONFIG.gameSeconds;paused=false;gameState=Object.keys(datasetStations).length?"ready":"loading";els.gamePanel.classList.add("hidden");els.resultPanel.classList.add("hidden");els.startPanel.classList.remove("hidden");els.answerInput.value="";updateStartStats()}
els.startBtn.addEventListener("click",startGame);els.againBtn.addEventListener("click",resetToReady);els.pauseBtn.addEventListener("click",togglePause);els.giveUpBtn.addEventListener("click",()=>{if(["playing","paused"].includes(gameState))finishGame("本局结束")});els.resetBtn.addEventListener("click",async()=>{if(["playing","paused"].includes(gameState)&&!confirm("确定要退出本局并重新加载五个站名集吗？"))return;resetToReady();await loadStations()});els.datasetOptions.addEventListener("change",updateSelectionUI);els.answerInput.addEventListener("compositionstart",()=>composing=true);els.answerInput.addEventListener("compositionend",()=>{composing=false;setTimeout(processInputValue,0)});els.answerInput.addEventListener("input",processInputValue);els.answerInput.addEventListener("paste",()=>setTimeout(processInputValue,0));els.answerInput.addEventListener("keydown",e=>{if(e.key==="Escape"){els.answerInput.value="";setInputState("READY","请输入一个汉字或数字")}if(e.key==="Enter"){e.preventDefault();processInputValue()}});loadStations();
